config/routes.rb
Rails.application.routes.draw do
  resources :micropigs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "micropigs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/micropig.rb
class Micropig < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/micropigs_controller.rb
class MicropigsController < ApplicationController
  before_action :set_micropig, only: %i[ show edit update destroy ]

  # GET /micropigs or /micropigs.json
  def index
    @micropigs = if params.key?(:age)
                    Micropig.where(age: params[:age])
                 else
                    Micropig.all
                 end
  end

  # GET /micropigs/1 or /micropigs/1.json
  def show
  end

  # GET /micropigs/new
  def new
    @micropig = Micropig.new(age: 1, notes: "Really a piglet")
  end

  # GET /micropigs/1/edit
  def edit
  end

  # POST /micropigs or /micropigs.json
  def create
    @micropig = Micropig.new(micropig_params)

    respond_to do |format|
      if @micropig.save
        format.html { redirect_to micropig_url(@micropig), notice: "Micropig was successfully created." }
        format.json { render :show, status: :created, location: @micropig }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @micropig.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /micropigs/1 or /micropigs/1.json
  def update
    respond_to do |format|
      if @micropig.update(micropig_params)
        format.html { redirect_to micropig_url(@micropig), notice: "Micropig was successfully updated." }
        format.json { render :show, status: :ok, location: @micropig }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @micropig.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /micropigs/1 or /micropigs/1.json
  def destroy
    @micropig.destroy!

    respond_to do |format|
      format.html { redirect_to micropigs_url, notice: "Micropig was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropig
      @micropig = Micropig.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def micropig_params
      params.require(:micropig).permit(:name, :age, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/micropigs_helper.rb
module MicropigsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdoptAMicropig</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/micropigs/_form.html.erb
<%= form_with(model: micropig) do |form| %>
  <% if micropig.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(micropig.errors.count, "error") %> prohibited this micropig from being saved:</h2>

      <ul>
        <% micropig.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :notes, style: "display: block" %>
    <%= form.text_area :notes %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/micropigs/_micropig.html.erb
<div id="<%= dom_id micropig %>">
  <p>
    <strong>Name:</strong>
    <%= micropig.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= micropig.age %>
  </p>

  <p>
    <strong>Notes:</strong>
    <%= micropig.notes %>
  </p>

</div>

app/views/micropigs/edit.html.erb
<h1>Editing micropig</h1>

<%= render "form", micropig: @micropig %>

<br>

<div>
  <%= link_to "Show this micropig", @micropig %> |
  <%= link_to "Back to micropigs", micropigs_path %>
</div>

app/views/micropigs/index.html.erb
<%= render "govuk_publishing_components/components/layout_header", {
  environment: "Development"
} %>

<p style="color: green"><%= notice %></p>

<div class="govuk-width-container">

<%= render "govuk_publishing_components/components/heading", {
  text: "Micropigs"
} %>

<%= render "govuk_publishing_components/components/table", {
  head: [ { text: "Name" }, { text: "Age", format: "numeric" }, { text: "" }],
  rows: @micropigs.map { |micropig|
    [
      { text: micropig.name },
      { text: micropig.age, format: "numeric" },
      { text: link_to("view", micropig) },
    ]
  },
} %>

<%= render "govuk_publishing_components/components/button", {
  text: "New micropig",
  href: new_micropig_path
} %>

</div>

app/views/micropigs/new.html.erb
<h1>New micropig</h1>

<%= render "form", micropig: @micropig %>

<br>

<div>
  <%= link_to "Back to micropigs", micropigs_path %>
</div>

app/views/micropigs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @micropig %>

<div>
  <%= link_to "Edit this micropig", edit_micropig_path(@micropig) %> |
  <%= link_to "Back to micropigs", micropigs_path %>

  <%= button_to "Destroy this micropig", @micropig, method: :delete %>
</div>